### PR TITLE
feat: add `pat` support for go client

### PR DESCRIPTION
**Pull request by stoffeastrom**

### CODE REVIEW

**Comment by stoffeastrom** [comment]
@zeroshade Put up a draft for adding `pat` support. Prepared an empty `middleware`. It works w/o doing anything in the `middleware`. Looking at the [python](https://github.com/dremio-hub/arrow-flight-client-examples/blob/main/python/example.py#L54-L63) looks like they are extracting `authorization` but in my initial tests this isn't passed at all.

**Comment by jduo** [comment]
> I removed the middleware since it's actually not needed to make it work.
> 
> @jduo are there any docs around this upcoming session management?

There aren't, but that's a good suggestion. I'll raise with our docs team.

**Comment by jduo** [comment]
FYI the go build is failing here:
https://github.com/dremio-hub/arrow-flight-client-examples/runs/5500661127?check_suite_focus=true#step:8:20

**Comment by stoffeastrom** [comment]
@jduo I bumped the go version matrix but it looks like someone needs to approve to run the workflows. The matrix is set to `1.16` / `1.17` since golang supports last two major version:

>Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. We fix critical problems, including [critical security problems](https://go.dev/security), in supported releases as needed by issuing minor revisions (for example, Go 1.6.1, Go 1.6.2, and so on).

**Pull request merged**
